# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Jan 29 14:48:12 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(883, 605)
        self.verticalLayout_11 = QtGui.QVBoxLayout(MainWindow)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(MainWindow)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.seleccionTab = QtGui.QWidget()
        self.seleccionTab.setObjectName(_fromUtf8("seleccionTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.seleccionTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.seleccionTab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setMargin(10)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.seleccionTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.temaEdit = QtGui.QLineEdit(self.seleccionTab)
        self.temaEdit.setObjectName(_fromUtf8("temaEdit"))
        self.horizontalLayout.addWidget(self.temaEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.temasList = QtGui.QListView(self.seleccionTab)
        self.temasList.setObjectName(_fromUtf8("temasList"))
        self.horizontalLayout_3.addWidget(self.temasList)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.temasSeleccionadosList = QtGui.QListView(self.seleccionTab)
        self.temasSeleccionadosList.setObjectName(_fromUtf8("temasSeleccionadosList"))
        self.verticalLayout_3.addWidget(self.temasSeleccionadosList)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.seleccionTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.desdeCheck = QtGui.QCheckBox(self.seleccionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desdeCheck.sizePolicy().hasHeightForWidth())
        self.desdeCheck.setSizePolicy(sizePolicy)
        self.desdeCheck.setMinimumSize(QtCore.QSize(16, 0))
        self.desdeCheck.setText(_fromUtf8(""))
        self.desdeCheck.setObjectName(_fromUtf8("desdeCheck"))
        self.horizontalLayout_4.addWidget(self.desdeCheck)
        self.desdeTime = QtGui.QTimeEdit(self.seleccionTab)
        self.desdeTime.setEnabled(False)
        self.desdeTime.setWrapping(False)
        self.desdeTime.setFrame(True)
        self.desdeTime.setReadOnly(False)
        self.desdeTime.setAccelerated(False)
        self.desdeTime.setObjectName(_fromUtf8("desdeTime"))
        self.horizontalLayout_4.addWidget(self.desdeTime)
        self.label_4 = QtGui.QLabel(self.seleccionTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.hastaCheck = QtGui.QCheckBox(self.seleccionTab)
        self.hastaCheck.setMinimumSize(QtCore.QSize(16, 0))
        self.hastaCheck.setText(_fromUtf8(""))
        self.hastaCheck.setObjectName(_fromUtf8("hastaCheck"))
        self.horizontalLayout_4.addWidget(self.hastaCheck)
        self.hastaTime = QtGui.QTimeEdit(self.seleccionTab)
        self.hastaTime.setEnabled(False)
        self.hastaTime.setObjectName(_fromUtf8("hastaTime"))
        self.horizontalLayout_4.addWidget(self.hastaTime)
        self.label_9 = QtGui.QLabel(self.seleccionTab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.algoritmoCombo = QtGui.QComboBox(self.seleccionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algoritmoCombo.sizePolicy().hasHeightForWidth())
        self.algoritmoCombo.setSizePolicy(sizePolicy)
        self.algoritmoCombo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.algoritmoCombo.setObjectName(_fromUtf8("algoritmoCombo"))
        self.horizontalLayout_4.addWidget(self.algoritmoCombo)
        self.tablasCheck = QtGui.QCheckBox(self.seleccionTab)
        self.tablasCheck.setObjectName(_fromUtf8("tablasCheck"))
        self.horizontalLayout_4.addWidget(self.tablasCheck)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.statusSelText = QtGui.QLabel(self.seleccionTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusSelText.setFont(font)
        self.statusSelText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statusSelText.setObjectName(_fromUtf8("statusSelText"))
        self.horizontalLayout_4.addWidget(self.statusSelText)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.seleccionTab, _fromUtf8(""))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.gridLayout = QtGui.QGridLayout(self.outputTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.webView = QtWebKit.QWebView(self.outputTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_4.addWidget(self.webView)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.printBtn = QtGui.QCommandLinkButton(self.outputTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printBtn.sizePolicy().hasHeightForWidth())
        self.printBtn.setSizePolicy(sizePolicy)
        self.printBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.printBtn.setDescription(_fromUtf8(""))
        self.printBtn.setObjectName(_fromUtf8("printBtn"))
        self.horizontalLayout_5.addWidget(self.printBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.outputTab, _fromUtf8(""))
        self.ubicacionesTab = QtGui.QWidget()
        self.ubicacionesTab.setEnabled(True)
        self.ubicacionesTab.setObjectName(_fromUtf8("ubicacionesTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ubicacionesTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_5 = QtGui.QLabel(self.ubicacionesTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_7.addWidget(self.label_5)
        self.ubicacionesTable = QtGui.QTableWidget(self.ubicacionesTab)
        self.ubicacionesTable.setRowCount(0)
        self.ubicacionesTable.setColumnCount(0)
        self.ubicacionesTable.setObjectName(_fromUtf8("ubicacionesTable"))
        self.verticalLayout_7.addWidget(self.ubicacionesTable)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ubicacionesTab, _fromUtf8(""))
        self.peliculasTab = QtGui.QWidget()
        self.peliculasTab.setObjectName(_fromUtf8("peliculasTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.peliculasTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_6 = QtGui.QLabel(self.peliculasTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.temasTable = QtGui.QTableWidget(self.peliculasTab)
        self.temasTable.setRowCount(0)
        self.temasTable.setColumnCount(0)
        self.temasTable.setObjectName(_fromUtf8("temasTable"))
        self.verticalLayout_8.addWidget(self.temasTable)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.peliculasTab, _fromUtf8(""))
        self.distanciasTab = QtGui.QWidget()
        self.distanciasTab.setObjectName(_fromUtf8("distanciasTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.distanciasTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_7 = QtGui.QLabel(self.distanciasTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.distanciasTable = QtGui.QTableWidget(self.distanciasTab)
        self.distanciasTable.setRowCount(0)
        self.distanciasTable.setColumnCount(0)
        self.distanciasTable.setObjectName(_fromUtf8("distanciasTable"))
        self.verticalLayout_9.addWidget(self.distanciasTable)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.distanciasTab, _fromUtf8(""))
        self.proyecionesTab = QtGui.QWidget()
        self.proyecionesTab.setObjectName(_fromUtf8("proyecionesTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.proyecionesTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_8 = QtGui.QLabel(self.proyecionesTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.proyeccionesTable = QtGui.QTableWidget(self.proyecionesTab)
        self.proyeccionesTable.setRowCount(0)
        self.proyeccionesTable.setColumnCount(0)
        self.proyeccionesTable.setObjectName(_fromUtf8("proyeccionesTable"))
        self.verticalLayout_10.addWidget(self.proyeccionesTable)
        self.gridLayout_6.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.proyecionesTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.statusLabel = QtGui.QLabel(MainWindow)
        self.statusLabel.setText(_fromUtf8(""))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.horizontalLayout_2.addWidget(self.statusLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.combinarBtn = QtGui.QPushButton(MainWindow)
        self.combinarBtn.setObjectName(_fromUtf8("combinarBtn"))
        self.horizontalLayout_2.addWidget(self.combinarBtn)
        self.salirBtn = QtGui.QPushButton(MainWindow)
        self.salirBtn.setObjectName(_fromUtf8("salirBtn"))
        self.horizontalLayout_2.addWidget(self.salirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog", None))
        self.label.setText(_translate("MainWindow", "Selecciones los contenidos que desea ver. Busque las peliculas ingresando parte del texto o buscandola en la lista.\n"
"Agregue cada pelicula a la selección y por último, haciendo click en el botón <b>\"\"Combinar\"\"</b> se generarán las combinaciones posibles.", None))
        self.label_2.setText(_translate("MainWindow", "Ingrese la película a buscar:", None))
        self.label_3.setText(_translate("MainWindow", "Desde las:", None))
        self.desdeTime.setDisplayFormat(_translate("MainWindow", "hh:mm", None))
        self.label_4.setText(_translate("MainWindow", "Hasta las:", None))
        self.hastaTime.setDisplayFormat(_translate("MainWindow", "hh:mm", None))
        self.label_9.setText(_translate("MainWindow", "Algoritmo:", None))
        self.tablasCheck.setText(_translate("MainWindow", "Ver tablas del sistema", None))
        self.statusSelText.setText(_translate("MainWindow", "No se han seleccionado peliculas aún", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.seleccionTab), _translate("MainWindow", "Selección", None))
        self.printBtn.setText(_translate("MainWindow", "Imprimir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), _translate("MainWindow", "Output", None))
        self.label_5.setText(_translate("MainWindow", "Ubicaciones", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ubicacionesTab), _translate("MainWindow", "Ubicaciones", None))
        self.label_6.setText(_translate("MainWindow", "Peliculas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.peliculasTab), _translate("MainWindow", "Peliculas", None))
        self.label_7.setText(_translate("MainWindow", "Distancias", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.distanciasTab), _translate("MainWindow", "Distancias", None))
        self.label_8.setText(_translate("MainWindow", "Distancias", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.proyecionesTab), _translate("MainWindow", "Proyecciones", None))
        self.combinarBtn.setText(_translate("MainWindow", "Combinar", None))
        self.salirBtn.setText(_translate("MainWindow", "Salir", None))

from PyQt4 import QtWebKit
